### ISSUE TITLE
Primary Navigation- Horizontal Alignment

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com#5]
![image](https://cloud.githubusercontent.com/assets/9142185/13469978/b401df4e-e077-11e5-8ec2-1bc2f06aaee6.png)

Align logo, Navigation, Phone Number and Quick Consult Button horizontally.

**Comment by mike3run** [comment]
They are aligned I'm thinking maybe the issue is with the logo.svg file and the viewbox.

![captura de pantalla 2016-03-02 a las 3 45 27 p m](https://cloud.githubusercontent.com/assets/7088511/13476530/e13185c6-e08d-11e5-8a4a-d07ced49617f.png)

You can see how it has some extra space in there so that could be a reason

**Comment by adam-s-p-** [comment]
Would it help you if I send over an updated logo asset?

**Comment by mike3run** [comment]
We should try it since everything else is vertically aligned :)

Thanks

**Comment by adam-s-p-** [comment]
Here is the cropped .png of the logo. Hope this helped!
![mbc-logo](https://cloud.githubusercontent.com/assets/9142185/13477068/a0b8dfac-e098-11e5-95c3-8719e6f908b0.png)

**Comment by mike3run** [comment]
![captura de pantalla 2016-03-02 a las 4 07 35 p m](https://cloud.githubusercontent.com/assets/7088511/13477212/e878b2fc-e090-11e5-982f-4626b601ff4d.png)

I think it did work
